### ISSUE TITLE
Make badman a private client like Weather

### ISSUE THREAD

**Issue by yeeterlol** [BadMan-Client/BadMan-Releases#15]
if retards keep reporting shit, make a application form and only accepted ones get access to the client. it stops termination & it makes it 500% easier to find who terminated the server. badman is a amazing client and the person who reported you was jealous that you had a better client then them

**Comment by hrkyr** [comment]
weather x badman is a hot asf ship aaaaaaaaaaaaaaah

**Comment by yeeterlol** [comment]
it doesn't have a fan fiction so it isnt

**Comment by Wendys-corp** [comment]
not gonna happen keep dreaming

**Comment by OldGreggo5081** [comment]
😉

**Comment by yeeterlol** [comment]
> not gonna happen keep dreaming

This was when Badman was terminated so I presented this idea
