### ISSUE TITLE
add airwalk to scaffold and fix no fall

### ISSUE THREAD

**Issue by unkowndumb** [BadMan-Client/BadMan-Releases#18]
it will be a great idea to add airwalk to scaffold and also fixing some issues with no fall thank u

**Comment by Turkeii** [comment]
> 
> 
> it will be a great idea to add airwalk to scaffold and also fixing some issues with no fall thank u

what nofall issues?

**Comment by unkowndumb** [comment]
> > it will be a great idea to add airwalk to scaffold and also fixing some issues with no fall thank u
> 
> what nofall issues?

No I just used it wrong but adding airwalk to scaffold will be super gg
