### ISSUE TITLE
discord link broken again (termed oof)

### ISSUE THREAD

**Issue by UltimateBoi** [BadMan-Client/BadMan-Releases#26]
pls greggory hepl us

**Comment by OldGreggo5081** [comment]
read the readme.md

**Comment by UltimateBoi** [comment]
ok

**Comment by UltimateBoi** [comment]
ik its termed but why dont you make new one?

**Comment by OldGreggo5081** [comment]
read the part at the bottom bruh

**Comment by UltimateBoi** [comment]
ok

**Comment by UltimateBoi** [comment]
ik its stopped dev but a community server would be nice

**Comment by UserRank** [comment]
can you add .bruh 2 @h

**Comment by UltimateBoi** [comment]
?

**Comment by UserRank** [comment]
> ?

https://github.com/BadMan-Client/BadMan-Releases/issues/26#issuecomment-1013929910

**Comment by UltimateBoi** [comment]
?
