### ISSUE TITLE
why is say open source!!!

### ISSUE THREAD

**Issue by shape1234** [BadMan-Client/BadMan-Releases#6]
i downlod badman source from <> Code and it give read me dot md!!! give sorce now i scammed>!!!

**Comment by DaEpicSwag** [comment]
Lmao GitHub does that automatically, also skid, please shut up.

**Comment by shape1234** [comment]
> Lmao GitHub does that automatically, also skid, please shut up.

stfu this joke flew over your head

**Comment by hrkyr** [comment]
> Lmao GitHub does that automatically, also skid, please shut up.

all of ur projects are in python bro and the ones that arent are forks LMFAO don't think u should determine who is a "skid"
