### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by AForApple834** [BadMan-Client/BadMan-Releases#7]
Whenever you get an error message and get disconnected you crash, get kicked you crash. Chest stealer crashes. pls fix

**Comment by OldGreggo5081** [comment]
the first one happens with minecraft not the client and chest stealer is die 👍

**Comment by shape1234** [comment]
pls figgs chest stealer😪😪😥😥😥😓😭😭😭😭😭😭😭😭😭😭😭😢😢😢😢😨😨😨😨😨😨😨😨😨😨
